// This is a simplified example of an org chart with a depth of 2.

import { TreeNodeType } from "./types";

// Note how deeper levels are defined recursively via the `children` property.
export const dummyTreeNodes: TreeNodeType[] = [{
    type: 'Data Source',
    childrenType: 'Matrik Anomaly',
    name: 'BRIMO',
    anomalyCount: 158,
    percentage: 100,
    children: [
      {
        type: 'Matrik Anomaly',
        childrenType: 'Service',
        name: 'Commercial',
        anomalyCount: 34,
        percentage: 100,
        children: [
          {
            type: 'Service',
            childrenType: 'Impected Service',
            name: '(Blank)',
            anomalyCount: 17,
            percentage: 100,
            children: [
                {
                  type: 'Impected Service',
                  childrenType: 'Security',
                  name: 'Access/Egress',
                  anomalyCount: 2,
                  percentage: 70,
                },
                {
                  type: 'Impected Service',
                  name: 'Clothing',
                  anomalyCount: 2,
                  percentage: 70,
                },
                {
                  type: 'Impected Service',
                  name: 'PPE',
                  anomalyCount: 2,
                  percentage: 70,
                },
                {
                  type: 'Impected Service',
                  name: 'Environment',
                  anomalyCount: 1,
                  percentage: 70,
                },
                {
                  type: 'Impected Service',
                  name: 'Ergonomics',
                  anomalyCount: 1,
                  percentage: 70,
                },
            ]
          },
          {
            type: 'Service',
            name: 'Equipment',
            anomalyCount: 4,
            percentage: 70,
          },
          {
            type: 'Service',
            name: 'Access/Egress',
            anomalyCount: 2,
            percentage: 70,
          },
          {
            type: 'Service',
            name: 'Clothing',
            anomalyCount: 2,
            percentage: 70,
          },
          {
            type: 'Service',
            name: 'PPE',
            anomalyCount: 2,
            percentage: 70,
          },
          {
            type: 'Service',
            name: 'Environment',
            anomalyCount: 1,
            percentage: 70,
          },
          {
            type: 'Service',
            name: 'Ergonomics',
            anomalyCount: 1,
            percentage: 70,
          },
          {
            type: 'Service',
            name: 'Guard/Barrier',
            anomalyCount: 1,
            percentage: 70,
          },
          {
            type: 'Service',
            name: 'Housekeeping',
            anomalyCount: 1,
            percentage: 70,
          },
          {
            type: 'Service',
            name: 'Keeper',
            anomalyCount: 1,
            percentage: 70,
          },
          {
            type: 'Service',
            name: 'Keeper Of The Light',
            anomalyCount: 1,
            percentage: 70,
          },
        ],
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'Entertainment',
        anomalyCount: 26,
        percentage: 80,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'Medical/Hospital',
        anomalyCount: 22,
        percentage: 70,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'Commercial/Mid-Rise',
        anomalyCount: 15,
        percentage: 70,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'School/University',
        anomalyCount: 14,
        percentage: 70,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'Higher Education',
        anomalyCount: 11,
        percentage: 70,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: '(Blank)',
        anomalyCount: 4,
        percentage: 70,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'Data Center',
        anomalyCount: 4,
        percentage: 70,
      },
    ],
  },
  {
    type: 'Aplikasi',
    childrenType: 'Aplikasi',
    name: 'BRIMO 2',
    anomalyCount: 158,
    percentage: 100,
    children: [
      {
        type: 'Databse',
        childrenType: 'Databse',
        name: 'Commercial',
        anomalyCount: 34,
        percentage: 100,
        children: [
          {
            type: 'Service',
            childrenType: 'Service',
            name: '(Blank)',
            anomalyCount: 17,
            percentage: 100,
          },
          {
            type: 'Service',
            childrenType: 'Service',
            name: 'Equipment',
            anomalyCount: 4,
            percentage: 70,
          },
          {
            type: 'Service',
            childrenType: 'Service',
            name: 'Access/Egress',
            anomalyCount: 2,
            percentage: 70,
          },
          {
            type: 'Service',
            childrenType: 'Service',
            name: 'Clothing',
            anomalyCount: 2,
            percentage: 70,
          },
          {
            type: 'Service',
            childrenType: 'Service',
            name: 'PPE',
            anomalyCount: 2,
            percentage: 70,
          },
          {
            type: 'Service',
            childrenType: 'Service',
            name: 'Environment',
            anomalyCount: 1,
            percentage: 70,
          },
          {
            type: 'Service',
            childrenType: 'Service',
            name: 'Ergonomics',
            anomalyCount: 1,
            percentage: 70,
          },
          {
            type: 'Service',
            childrenType: 'Service',
            name: 'Guard/Barrier',
            anomalyCount: 1,
            percentage: 70,
          },
          {
            type: 'Service',
            childrenType: 'Service',
            name: 'Housekeeping',
            anomalyCount: 1,
            percentage: 70,
          },
        ],
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'Entertainment',
        anomalyCount: 26,
        percentage: 80,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'Medical/Hospital',
        anomalyCount: 22,
        percentage: 70,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'Commercial/Mid-Rise',
        anomalyCount: 15,
        percentage: 70,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'School/University',
        anomalyCount: 14,
        percentage: 70,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'Higher Education',
        anomalyCount: 11,
        percentage: 70,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: '(Blank)',
        anomalyCount: 4,
        percentage: 70,
      },
      {
        type: 'Matrik Anomaly',
        childrenType: 'Matrik Anomaly',
        name: 'Data Center',
        anomalyCount: 4,
        percentage: 70,
      },
    ],
  },
];
  